config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'index#index'
  
  get "/companies", to: "companies#index"
  get "/companies/:id", to: "companies#show"

  get "/jobs", to: "jobs#index"
  get "/jobs/:id", to: "jobs#show"

  get '/admin', to: 'admin#index'
  get '/admin/company', to: 'admin#edit', as: 'admin_edit'
  patch '/admin/company', to: 'admin#update'

  namespace :admin do
    get '/jobs/new', to: 'jobs#new'
    post '/jobs/new', to: 'jobs#create', as: 'job_new'
    get '/jobs/:id', to: 'jobs#edit', as: 'job'
    patch '/jobs/:id', to: 'jobs#update'
    delete '/jobs/:id', to: 'jobs#destroy', as: 'job_delete'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::AdminController
  def edit
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    @job.company_id = 1
  end

  def create
    @job = Job.new(
      title: params[:job][:title],
      content: params[:job][:content],
      condition_requirements: params[:job][:condition_requirements],
      company_benefits: params[:job][:company_benefits],
      salary_range: params[:job][:salary_range],
      is_open: params[:job][:is_open].to_s == "true",
      company_id: params[:job][:company_id].to_f
    )

    if @job.save
      redirect_to '/admin'
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    @job.content = params[:job][:content]
    @job.condition_requirements = params[:job][:condition_requirements]
    @job.company_benefits = params[:job][:company_benefits]
    @job.salary_range = params[:job][:salary_range]
    @job.is_open = params[:job][:is_open]

    if @job.save
      redirect_to '/admin'
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to '/admin'
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @jobs = Job.where(company_id: 1)
  end

  def edit
    @company = Company.find(1)
  end

  def update
    @company = Company.find(1)

    @company.profile = params[:company][:profile]
    @company.philosophy = params[:company][:philosophy]
    @company.media_reports = params[:company][:media_reports]
    @company.salary_benefits = params[:company][:salary_benefits]

    if @company.save
      redirect_to '/companies/1'
    else
      render :edit
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @companies = Company.all
    @jobs = Job.all.select { |job| job.is_open }
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all.select { |job| job.is_open }
  end

  def show
    @job = Job.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/edit.html.erb
<%= form_for @company, :url => admin_edit_path, method: :patch  do |form| %>
  <div class="profile">
    <p class="profile-title"><%= @company.title %></p>
      <p class="detail detail-description">公司介紹</p>
      <%= form.text_area :profile, class: 'detail detail-content detail-edit' %><br>
      <p class="detail detail-description">公司理念</p>
      <%= form.text_area :philosophy, class: 'detail detail-content detail-edit' %><br>
      <p class="detail detail-description">媒體報導</p>
      <%= form.text_area :media_reports, class: 'detail detail-content detail-edit' %><br>
      <p class="detail detail-description">薪資福利</p>
      <%= form.text_area :salary_benefits, class: 'detail detail-content detail-edit' %><br>
  </div>
  <div class="apply-block">
    <button type="submit" class="button" >存擋</button>
  </div>
<% end %>

app/views/admin/index.html.erb
<div class="admin-title">
  <button class="button" onclick="location.href='/admin/company'">
    管理公司資訊
  </button>
  <button class="button add-job" onclick="location.href='/admin/jobs/new'">
    新增職缺
  </button>
</div>

<div class="admin-jobs">
  <div class="list">
    <% @jobs.each do |job| %>
      <div class="list-item">
        <div class="modify-item" onclick="location.href='/admin/jobs/<%= job.id %>'">
          <%= job.title %>
        </div>
        <div class="toggle-button <%= job.is_open ? 'open' : '' %>">
          <div class="toggle-circle">
          </div>
        </div>
        <i class="fas fa-trash-alt">
          <%= link_to "", admin_job_delete_path(job),
          method: :delete,
          data: { confirm: "你確定要刪除嗎？" } %>
        </i>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/jobs/edit.html.erb
<%= form_for @job, :url => admin_job_path, method: :patch  do |form| %>
  <div class="profile">
    <div class="job-status-block">
      <p class="text">職缺狀態</p>
      <div class="toggle-button">
        <label class="button">開啟
          <%= form.radio_button :is_open, true %>
          <div class="checkmark">開啟</div>
        </label>
        <label class="button">關閉
          <%= form.radio_button :is_open, false %>
          <div class="checkmark">關閉</div>
        </label>
      </div>
    </div>
    <p class="profile-title"><%= @job.title %></p>
    <p class="detail detail-description">工作內容</p>
    <%= form.text_area :content, class: 'detail detail-content detail-edit' %><br>
    <p class="detail detail-description">條件要求</p>
    <%= form.text_area :condition_requirements, class: 'detail detail-content detail-edit' %><br>
    <p class="detail detail-description">公司福利</p>
    <%= form.text_area :company_benefits, class: 'detail detail-content detail-edit' %><br>
    <p class="detail detail-description">薪資範圍</p>
    <%= form.text_area :salary_range, class: 'detail detail-content detail-edit' %><br>
    <div class="apply-block">
      <button type="submit" class="button" >存擋</button>
    </div>
  </div>
<% end %>

app/views/admin/jobs/new.html.erb
<%= form_for @job, :url => admin_jobs_new_path, method: :post  do |form| %>
  <%= form.hidden_field :company_id %>
  <div class="profile">
    <div class="job-status-block">
      <p class="text">職缺狀態</p>
      <div class="toggle-button">
        <label class="button">開啟
          <%= form.radio_button :is_open, true %>
          <div class="checkmark">開啟</div>
        </label>
        <label class="button">關閉
          <%= form.radio_button :is_open, false %>
          <div class="checkmark">關閉</div>
        </label>
      </div>
    </div>
    <%= form.text_field :title, class: 'profile-title jobs-title-edit' %>
    <p class="detail detail-description">工作內容</p>
    <%= form.text_area :content, class: 'detail detail-content detail-edit' %><br>
    <p class="detail detail-description">條件要求</p>
    <%= form.text_area :condition_requirements, class: 'detail detail-content detail-edit' %><br>
    <p class="detail detail-description">公司福利</p>
    <%= form.text_area :company_benefits, class: 'detail detail-content detail-edit' %><br>
    <p class="detail detail-description">薪資範圍</p>
    <%= form.text_area :salary_range, class: 'detail detail-content detail-edit' %><br>
    <div class="apply-block">
      <button type="submit" class="button" >存擋</button>
    </div>
  </div>
<% end %>

app/views/companies/index.html.erb
<p class="list-title">公司列表</p>
<div class="list">
  <% @companies.each do |company| %>
    <div class="list-item" onclick="location.href='/companies/<%= company.id %>'">
      <%= company.title %>
    </div>
  <% end %>
</div>

app/views/companies/show.html.erb
<div class="profile">
  <p class="profile-title"><%= @company.title %></p>
    <p class="detail detail-description">公司介紹</p>
    <p class="detail detail-content"><%= @company.profile %></p>
    <p class="detail detail-description">公司理念</p>
    <p class="detail detail-content"><%= @company.philosophy %></p>
    <p class="detail detail-description">媒體報導</p>
    <p class="detail detail-content"><%= @company.media_reports %></p>
    <p class="detail detail-description">薪資福利</p>
    <p class="detail detail-content"><%= @company.salary_benefits %></p>
    <p class="detail detail-description">目前職缺</p>
    <div class="list">
      <% @company.jobs.select { |job| job.is_open }.each do |job| %>
        <div class="list-item" onclick="location.href='/jobs/<%= job.id %>'">
          <%= job.title %>
        </div>
      <% end %>
    </div>
</div>

app/views/index/index.html.erb
<div class="grid">
  <p class="grid-title">精選公司</p>
  <a href="/companies" class="grid-more">更多公司</a>
  <div class="grid-content">
    <% @companies.sort_by {rand}[0...5].each do |company| %>
      <div class="grid-item" onclick="location.href='/companies/<%= company.id %>'">
        <p class="grid-text">
          <%= company.title %>
        </p>
      </div>
    <% end %>
  </div>
</div>

<div class="grid">
  <p class="grid-title">精選職缺</p>
  <a href="/jobs" class="grid-more">更多職缺</a>
  <div class="grid-content">
    <% @jobs.sort_by {rand}[0...10].each do |job| %>
      <div class="grid-item" onclick="location.href='/jobs/<%= job.id %>'">
        <p class="grid-text">
          <%= job.title %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/index.html.erb
<p class="list-title">職缺列表</p>
<div class="list">
  <% @jobs.each do |job| %>
    <div class="list-item" onclick="location.href='/jobs/<%= job.id %>'">
      <%= job.title %>
    </div>
  <% end %>
</div>

app/views/jobs/show.html.erb
<div class="profile">
  <p class="title"><%= @job.title %></p>
    <p class="detail detail-description">工作內容</p>
    <p class="detail detail-content"><%= @job.content %></p>
    <p class="detail detail-description">條件要求</p>
    <p class="detail detail-content"><%= @job.condition_requirements %></p>
    <p class="detail detail-description">公司福利</p>
    <p class="detail detail-content"><%= @job.company_benefits %></p>
    <p class="detail detail-description">薪資範圍</p>
    <p class="detail detail-content"><%= @job.salary_range %></p>
</div>
<div class="apply-block">
  <button class="button">現在應徵</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3643bf9186.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>